ALTER TABLE acc ADD COLUMN `src` char(64) DEFAULT NULL;
ALTER TABLE acc ADD COLUMN `dst` char(64) DEFAULT NULL ;
ALTER TABLE acc ADD COLUMN `channel` char(128) DEFAULT NULL ;
ALTER TABLE acc ADD COLUMN `dstchannel` char(128) DEFAULT NULL ;
ALTER TABLE acc ADD COLUMN `direction` char(128) DEFAULT NULL ;

